/* generated by: ./quest-20040603/src/quest.opt -gcc -n 2 -s 10
 * $Id: gcc-2.95.3-00.c 3 2006-04-29 13:17:19Z lindig $
 */
/* 
Reading specs from /usr/local/lib/gcc-lib/sparc-sun-solaris2.8/2.95.3/specs
gcc version 2.95.3 20010315 (release)
SunOS barolo.ibr.cs.tu-bs.de 5.8 Generic_108528-29 sun4u sparc
gcc -O3 gcc-2.95.3-solaris.c && ./a.out
failed in gcc-2.95.3-solaris.c: 140
*/


extern int printf (char *, ...);

static int errors = 0;

static void failed( int line )
{ printf ("failed in %s: %d\n", __FILE__, line); errors++; }

static
struct x002_tag_k
{
    union x002_tag_j
    {
        struct x002_tag_i {  } x002_var_n;
        struct x002_tag_h {  } x002_var_m;
        struct x002_tag_g {  } x002_var_l;
    }
    x002_var_o;
    struct x002_tag_f {  } x002_var_k;
}
x002_var_p
=
    { { {  } }, {  } };

static int x002_var_e = 606233618;

static double x002_var_f = 34461.257140;

static unsigned long int x002_var_g = 1205937094UL;

static
union x002_tag_e
{ union x002_tag_d {  } x002_var_d; double *x002_var_c; }
*x002_var_h
=
    (union x002_tag_e *) 1585249285U;

static
struct x002_tag_c
{ union x002_tag_b {  } x002_var_b; struct x002_tag_a {  } *x002_var_a; }
x002_var_i
=
    { {  }, (struct x002_tag_a *) 1760399982U };

static double x002_var_j = 52471.885403;

struct x002_tag_k
x002_fun_a(
    int x002_par_a,
    double x002_par_b,
    unsigned long int x002_par_c,
    union x002_tag_e *x002_par_d,
    struct x002_tag_c x002_par_e,
    double x002_par_f
)
{
    if (x002_var_e !=  x002_par_a) failed (__LINE__);
    if (x002_var_f !=  x002_par_b) failed (__LINE__);
    if (x002_var_g !=  x002_par_c) failed (__LINE__);
    if (x002_var_h !=  x002_par_d) failed (__LINE__);
    if (x002_var_i.x002_var_a !=  x002_par_e.x002_var_a) failed (__LINE__);
    if (x002_var_j !=  x002_par_f) failed (__LINE__);
    return x002_var_p;
}

static void x002_fun_b(  )
{
    struct x002_tag_k x002_var_q;
    x002_var_q
    =
    x002_fun_a
        (x002_var_e,
        x002_var_f,
        x002_var_g,
        x002_var_h,
        x002_var_i,
        x002_var_j);
}

static double x001_var_t = 77982.689756;

static
union x001_tag_g
{
    float x001_var_m;
    struct x001_tag_f {  } x001_var_l;
    union x001_tag_e
    {
        float x001_var_j;
        union x001_tag_d
        {
            double x001_var_h;
            unsigned short int x001_var_g;
            float x001_var_f;
        }
        x001_var_i;
        struct x001_tag_c { float x001_var_d; } x001_var_e;
    }
    x001_var_k;
}
x001_var_n[1]
=
    { { 62608.579745 } };

static unsigned short int x001_var_o = 50522;

static
union x001_tag_b { float x001_var_c[1]; } x001_var_p =
    { { 30798.997606 } };

static float **x001_var_q = (float **) 1004036413U;

static double *(**x001_var_r)[1] = (double *(**)[1]) 1172380878U;

static
struct x001_tag_a
{ short int x001_var_b[1]; short int x001_var_a; }
x001_var_s[1]
=
    { { { 22544 }, 11378 } };

double
x001_fun_a(
    union x001_tag_g x001_par_a[1],
    unsigned short int x001_par_b,
    union x001_tag_b x001_par_c,
    float **x001_par_d,
    double *(**x001_par_e)[1],
    struct x001_tag_a x001_par_f[1]
)
{
    if (x001_var_n[0].x001_var_m !=  x001_par_a[0].x001_var_m)
        failed (__LINE__);
    if (x001_var_o !=  x001_par_b) failed (__LINE__);
    if (x001_var_p.x001_var_c[0] !=  x001_par_c.x001_var_c[0])
        failed (__LINE__);
    if (x001_var_q !=  x001_par_d) failed (__LINE__);
    if (x001_var_r !=  x001_par_e) failed (__LINE__);
    if (x001_var_s[0].x001_var_b[0] !=  x001_par_f[0].x001_var_b[0])
        failed (__LINE__);
    if (x001_var_s[0].x001_var_a !=  x001_par_f[0].x001_var_a)
        failed (__LINE__);
    return x001_var_t;
}

static void x001_fun_b(  )
{
    double x001_var_u;
    x001_var_u
    =
    x001_fun_a
        (x001_var_n,
        x001_var_o,
        x001_var_p,
        x001_var_q,
        x001_var_r,
        x001_var_s);
    if (x001_var_t !=  x001_var_u) failed (__LINE__);
}

int main( int argc, char **argv )
{ x002_fun_b (); x001_fun_b (); return errors; }
