/* generated by: ./ccg -n 3 */
/* bash-2.05b$ uname -a
 * IRIX64 mars 6.5 10070055 IP27
 * 
 * bash-2.05b$ cc -O3 -o foo mipspro-7.3.1.3m.c 
 * bash-2.05b$ ./foo 
 * failed in mipspro-7.3.1.3m.c: 100
 * failed in mipspro-7.3.1.3m.c: 106
 */

extern int printf (char *, ...);
static int errors = 0;
union x001_tag_m
{
    struct x001_tag_l
    { double x001_var_bb; unsigned char x001_var_ba; double x001_var_z; }
    x001_var_bc;
}
*x001_var_bd[1]
=
    { (union x001_tag_m *) 1662426883U };
union x001_tag_k
{
    double x001_var_y;
    float x001_var_x;
    struct x001_tag_j
    { double *x001_var_v; short int *x001_var_u; }
    x001_var_w[1];
}
x001_var_be
=
    { 26384.884728 };
struct x001_tag_i
{
    struct x001_tag_h
    { double x001_var_s; double x001_var_r; unsigned int x001_var_q; }
    *x001_var_t;
    union x001_tag_g { char x001_var_o; char x001_var_n; } (*x001_var_p)[1];
    struct x001_tag_f
    {
        struct x001_tag_e
        {
            union x001_tag_d { double x001_var_j; } x001_var_k;
            union x001_tag_c { char x001_var_h; } x001_var_i;
            struct x001_tag_b
            { unsigned char x001_var_f; float x001_var_e; }
            x001_var_g;
        }
        x001_var_l;
        struct x001_tag_a
        {
            float x001_var_c;
            unsigned long int x001_var_b;
            long int x001_var_a;
        }
        x001_var_d[2];
    }
    x001_var_m;
}
x001_var_bf
=
    {
        (struct x001_tag_h *) 378049007U,
        (union x001_tag_g (*)[1]) 684517025U,
        {
            { { 67168.306109 }, { '\x39' }, { '\x50', 3246.139025 } },
            {
                { 67034.326199, 1475763134UL, 1543164726L },
                { 82556.788539, 1010475427UL, 1013514792L }
            }
        }
    };
static
void
x001_fun_b(
    union x001_tag_m *a1[1],
    union x001_tag_k a2,
    struct x001_tag_i a3
)
{
    if (x001_var_bd[0] !=  a1[0])
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_be.x001_var_y !=  a2.x001_var_y)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_t !=  a3.x001_var_t)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_p !=  a3.x001_var_p)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_l.x001_var_k.x001_var_j !=
         a3.x001_var_m.x001_var_l.x001_var_k.x001_var_j)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_l.x001_var_i.x001_var_h !=
         a3.x001_var_m.x001_var_l.x001_var_i.x001_var_h)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_l.x001_var_g.x001_var_f !=
         a3.x001_var_m.x001_var_l.x001_var_g.x001_var_f)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_l.x001_var_g.x001_var_e !=
         a3.x001_var_m.x001_var_l.x001_var_g.x001_var_e)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[1].x001_var_c !=
         a3.x001_var_m.x001_var_d[1].x001_var_c)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[0].x001_var_c !=
         a3.x001_var_m.x001_var_d[0].x001_var_c)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[1].x001_var_b !=
         a3.x001_var_m.x001_var_d[1].x001_var_b)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[0].x001_var_b !=
         a3.x001_var_m.x001_var_d[0].x001_var_b)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[1].x001_var_a !=
         a3.x001_var_m.x001_var_d[1].x001_var_a)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x001_var_bf.x001_var_m.x001_var_d[0].x001_var_a !=
         a3.x001_var_m.x001_var_d[0].x001_var_a)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
}
static void x001_fun_a(  )
{ x001_fun_b (x001_var_bd, x001_var_be, x001_var_bf); }
static void x002_fun_b(  ) {  }
static void x002_fun_a(  ) { x002_fun_b (); }
long int x003_var_j = 1145242287L;
union x003_tag_f { double x003_var_i; } ***x003_var_k =
    (union x003_tag_f ***) 1104557492U;
struct x003_tag_e
{
    struct x003_tag_d
    { unsigned short int x003_var_g; double x003_var_f; }
    x003_var_h;
}
(*x003_var_l)[1]
=
    (struct x003_tag_e (*)[1]) 1329856296U;
double x003_var_m = 69404.479060;
union x003_tag_c
{
    struct x003_tag_b
    {
        struct x003_tag_a
        { unsigned long int x003_var_c; short int *x003_var_b; }
        x003_var_d;
    }
    x003_var_e;
    float x003_var_a;
}
x003_var_n
=
    { { { 608822871UL, (short int *) 1193929328U } } };
static
void
x003_fun_b(
    long int a1,
    union x003_tag_f ***a2,
    struct x003_tag_e (*a3)[1],
    double a4,
    union x003_tag_c a5
)
{
    if (x003_var_j !=  a1)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x003_var_k !=  a2)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x003_var_l !=  a3)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x003_var_m !=  a4)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x003_var_n.x003_var_e.x003_var_d.x003_var_c !=
         a5.x003_var_e.x003_var_d.x003_var_c)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
    if (x003_var_n.x003_var_e.x003_var_d.x003_var_b !=
         a5.x003_var_e.x003_var_d.x003_var_b)
    { printf ("failed in %s: %d\n", __FILE__, __LINE__); errors++; }
}
static void x003_fun_a(  )
{ x003_fun_b (x003_var_j, x003_var_k, x003_var_l, x003_var_m, x003_var_n); }
int main( int argc, char **argv )
{ x001_fun_a (); x002_fun_a (); x003_fun_a (); return errors; }
