/* generated by: ../quest-20040603/src/quest.opt -gcc -n 5 -s 10
 * $Id: gcc-3.3.3-00.c 3 2006-04-29 13:17:19Z lindig $
 */
/* gcc version 3.3.3 (Debian 20040401) 
 * gcc -c -O3 foo.c
foo.c: In function `main':
foo.c:263: error: unable to find a register to spill in class `AREG'
foo.c:263: error: this is the insn:
(jump_insn:HI 74 68 470 0 0x401d42c0 (parallel [
            (set (pc)
                (if_then_else (eq (reg/v:SF 8 st(0) [73])
                        (reg/v:SF 8 st(0) [73]))
                    (label_ref 92)
                    (pc)))
            (clobber (reg:CCFP 18 fpsr))
            (clobber (reg:CCFP 17 flags))
            (clobber (scratch:HI))
        ]) 366 {*fp_jcc_5} (insn_list 66 (nil))
    (expr_list:REG_DEAD (reg/v:SF 8 st(0) [73])
        (expr_list:REG_UNUSED (reg:CCFP 18 fpsr)
            (expr_list:REG_UNUSED (reg:CCFP 17 flags)
                (expr_list:REG_UNUSED (scratch:HI)
                    (expr_list:REG_BR_PROB (const_int 7000 [0x1b58])
                        (nil)))))))
foo.c:263: confused by earlier errors, bailing out
*/

extern int printf (char *, ...);

static int errors = 0;

static void failed( int line )
{ printf ("failed in %s: %d\n", __FILE__, line); errors++; }

static
union x005_tag_c
{
    union x005_tag_b
    { unsigned short int x005_var_c; short int *x005_var_b; }
    *x005_var_d;
    union x005_tag_a {  } x005_var_a;
}
x005_var_e
=
    { (union x005_tag_b *) 762849179U };

union x005_tag_c x005_fun_a(  ) { return x005_var_e; }

static void x005_fun_b(  )
{
    union x005_tag_c x005_var_f;
    x005_var_f = x005_fun_a ();
    if (x005_var_e.x005_var_d !=  x005_var_f.x005_var_d) failed (__LINE__);
}

static struct x004_tag_c {  } *x004_var_f = (struct x004_tag_c *) 180432890U;

static struct x004_tag_b {  } x004_var_a = {  };

static float x004_var_b = 47754.456857;

static float x004_var_c = 50253.808627;

static
union x004_tag_a {  } (*x004_var_d)[2] =
    (union x004_tag_a (*)[2]) 1329781311U;

static unsigned short int x004_var_e[1] = { 28356 };

struct x004_tag_c *
x004_fun_a(
    struct x004_tag_b x004_par_a,
    float x004_par_b,
    float x004_par_c,
    union x004_tag_a (*x004_par_d)[2],
    unsigned short int x004_par_e[1]
)
{
    if (x004_var_b !=  x004_par_b) failed (__LINE__);
    if (x004_var_c !=  x004_par_c) failed (__LINE__);
    if (x004_var_d !=  x004_par_d) failed (__LINE__);
    if (x004_var_e[0] !=  x004_par_e[0]) failed (__LINE__);
    return x004_var_f;
}

static void x004_fun_b(  )
{
    struct x004_tag_c *x004_var_g;
    x004_var_g
    =
    x004_fun_a (x004_var_a, x004_var_b, x004_var_c, x004_var_d, x004_var_e);
    if (x004_var_f !=  x004_var_g) failed (__LINE__);
}

static unsigned char x003_var_y = '\x27';

static
struct x003_tag_h
{
    short int *x003_var_q;
    float (*x003_var_p)[2];
    struct x003_tag_g
    { float x003_var_n; short int x003_var_m; }
    x003_var_o[2][1];
}
x003_var_r
=
    {
        (short int *) 696155607U,
        (float (*)[2]) 976601271U,
        { { { 32177.564979, 15815 } }, { { 80545.556101, 10619 } } }
    };

static struct x003_tag_f {  } x003_var_s = {  };

static
union x003_tag_e
{
    float x003_var_l;
    struct x003_tag_d { int x003_var_j; char x003_var_i; } x003_var_k;
    float x003_var_h;
}
*x003_var_t[1]
=
    { (union x003_tag_e *) 1129469617U };

static unsigned char x003_var_u = '\x63';

static char x003_var_v = '\x3c';

static
struct x003_tag_c
{
    union x003_tag_b
    {
        float *x003_var_f;
        float x003_var_e;
        struct x003_tag_a { float x003_var_c; float x003_var_b; } x003_var_d;
    }
    x003_var_g;
    char *x003_var_a;
}
x003_var_w[2]
=
    {
        { { (float *) 1634131387U }, (char *) 2127905362U },
        { { (float *) 1755455182U }, (char *) 553417958U }
    };

static float *x003_var_x = (float *) 1000993005U;

unsigned char
x003_fun_a(
    struct x003_tag_h x003_par_a,
    struct x003_tag_f x003_par_b,
    union x003_tag_e *x003_par_c[1],
    unsigned char x003_par_d,
    char x003_par_e,
    struct x003_tag_c x003_par_f[2],
    float *x003_par_g
)
{
    if (x003_var_r.x003_var_q !=  x003_par_a.x003_var_q) failed (__LINE__);
    if (x003_var_r.x003_var_p !=  x003_par_a.x003_var_p) failed (__LINE__);
    if (x003_var_r.x003_var_o[1][0].x003_var_n !=
         x003_par_a.x003_var_o[1][0].x003_var_n)
        failed (__LINE__);
    if (x003_var_r.x003_var_o[0][0].x003_var_n !=
         x003_par_a.x003_var_o[0][0].x003_var_n)
        failed (__LINE__);
    if (x003_var_r.x003_var_o[1][0].x003_var_m !=
         x003_par_a.x003_var_o[1][0].x003_var_m)
        failed (__LINE__);
    if (x003_var_r.x003_var_o[0][0].x003_var_m !=
         x003_par_a.x003_var_o[0][0].x003_var_m)
        failed (__LINE__);
    if (x003_var_t[0] !=  x003_par_c[0]) failed (__LINE__);
    if (x003_var_u !=  x003_par_d) failed (__LINE__);
    if (x003_var_v !=  x003_par_e) failed (__LINE__);
    if (x003_var_w[1].x003_var_g.x003_var_f !=
         x003_par_f[1].x003_var_g.x003_var_f)
        failed (__LINE__);
    if (x003_var_w[0].x003_var_g.x003_var_f !=
         x003_par_f[0].x003_var_g.x003_var_f)
        failed (__LINE__);
    if (x003_var_w[1].x003_var_a !=  x003_par_f[1].x003_var_a)
        failed (__LINE__);
    if (x003_var_w[0].x003_var_a !=  x003_par_f[0].x003_var_a)
        failed (__LINE__);
    if (x003_var_x !=  x003_par_g) failed (__LINE__);
    return x003_var_y;
}

static void x003_fun_b(  )
{
    unsigned char x003_var_z;
    x003_var_z
    =
    x003_fun_a
        (x003_var_r,
        x003_var_s,
        x003_var_t,
        x003_var_u,
        x003_var_v,
        x003_var_w,
        x003_var_x);
    if (x003_var_y !=  x003_var_z) failed (__LINE__);
}

static unsigned long int x002_var_e = 447083500UL;

static unsigned long int x002_var_a = 2040204534UL;

static struct x002_tag_a {  } x002_var_b = {  };

static char x002_var_c = '\x63';

static float x002_var_d = 81829.967437;

unsigned long int
x002_fun_a(
    unsigned long int x002_par_a,
    struct x002_tag_a x002_par_b,
    char x002_par_c,
    float x002_par_d
)
{
    if (x002_var_a !=  x002_par_a) failed (__LINE__);
    if (x002_var_c !=  x002_par_c) failed (__LINE__);
    if (x002_var_d !=  x002_par_d) failed (__LINE__);
    return x002_var_e;
}

static void x002_fun_b(  )
{
    unsigned long int x002_var_f;
    x002_var_f = x002_fun_a (x002_var_a, x002_var_b, x002_var_c, x002_var_d);
    if (x002_var_e !=  x002_var_f) failed (__LINE__);
}

static struct x001_tag_b {  } x001_var_f = {  };

static unsigned int x001_var_a[1][1] = { { 978190140U } };

static float *x001_var_b = (float *) 1459857667U;

static double (*x001_var_c)[1] = (double (*)[1]) 17613317U;

static struct x001_tag_a {  } x001_var_d = {  };

static unsigned char x001_var_e = '\x1';

struct x001_tag_b
x001_fun_a(
    unsigned int x001_par_a[1][1],
    float *x001_par_b,
    double (*x001_par_c)[1],
    struct x001_tag_a x001_par_d,
    unsigned char x001_par_e
)
{
    if (x001_var_a[0][0] !=  x001_par_a[0][0]) failed (__LINE__);
    if (x001_var_b !=  x001_par_b) failed (__LINE__);
    if (x001_var_c !=  x001_par_c) failed (__LINE__);
    if (x001_var_e !=  x001_par_e) failed (__LINE__);
    return x001_var_f;
}

static void x001_fun_b(  )
{
    struct x001_tag_b x001_var_g;
    x001_var_g
    =
    x001_fun_a (x001_var_a, x001_var_b, x001_var_c, x001_var_d, x001_var_e);
}

int main( int argc, char **argv )
{
    x005_fun_b ();
    x004_fun_b ();
    x003_fun_b ();
    x002_fun_b ();
    x001_fun_b ();
    return errors;
}
