/* $Id: quest.lua 3 2006-04-29 13:17:19Z lindig $ */
/* ./main.native -n 1 -test gcc */

/*
 * This code is generated by Quest and is intended to find
 * inconsistencies in C compilers. To learn more about Quest, visit:
 *
 *      http://www.st.cs.uni-sb.de/~lindig/src/quest/
 */

/* These macros are defined in Lua string Quest.header, which may be
 * re-defined from the quest command line or in file quest.lua. 
 */
#ifndef QUEST_FAILED
#include <assert.h>
#define QUEST_ASSERT(x) assert(x)
#else
#define QUEST_ASSERT(x) if (!(x)) failed(__LINE__)
#endif

#include <stdio.h>

#include <stdarg.h>

static int errors = 0;
static void failed(int line)
{  printf("failed in %s: %d\n", __FILE__, line); errors++; }
static
    struct bt7
    {
        long long int b20;
        struct bt5
        {
            unsigned short int b12;
            signed b13:2;
            signed b14:7;
            float b15;
            unsigned long int b16;
        }
        b21;
        union bt6 { double b17; float b18; float b19; } b22;
    }
    b23
        = {1324116974L, {46455, 0, 42, 87461.76, 416301572UL}, {12575.24}};
static char b27 = '\x7b';
static short int b28 = 19258;
static unsigned short int b29 = 44755;
static double b30 = 32710.92;
static double b31[0][0] = {};
static char *b32[1] = {(char *) 845059068U};
static
    struct bt4
    {
        union bt2 {  } b5;
        signed b6:9;
        signed b7:4;
        signed b8:11;
        signed b9:7;
        float b10;
        union bt3 { float b4; } b11;
    }
    b33
        = {{}, 50, 1, 757, 55, 82963.46, {67859.05}};
static
    struct bt0 { short int b0; float b1; } *b24 = (struct bt0 *) 585878418U;
static long long int b25 = 220203681L;
static
    union bt1 { unsigned char *b2; double b3; } b26
        = {(unsigned char *) 2003179215U};
struct bt7 
callee_b0f(char bp7,
    short int bp8,
    unsigned short int bp9,
    double bp10,
    double bp11[0][0],
    char *bp12[1],
    struct bt4 bp13,
    ...)
{
    va_list ap;
    typedef struct bt0 *bd0;
    typedef long long int bd1;
    typedef union bt1 bd2;
    bd0 b34;
    bd1 b35;
    bd2 b36;
    
    /* seed: 824 */
    va_start(ap, bp13);
    QUEST_ASSERT(b27 == bp7);
    QUEST_ASSERT(b28 == bp8);
    QUEST_ASSERT(b29 == bp9);
    QUEST_ASSERT(b30 == bp10);
    QUEST_ASSERT(b32[0] == bp12[0]);
    QUEST_ASSERT(b33.b6 == bp13.b6);
    QUEST_ASSERT(b33.b7 == bp13.b7);
    QUEST_ASSERT(b33.b8 == bp13.b8);
    QUEST_ASSERT(b33.b9 == bp13.b9);
    QUEST_ASSERT(b33.b10 == bp13.b10);
    QUEST_ASSERT(b33.b11.b4 == bp13.b11.b4);
    b34 = va_arg(ap, bd0);
    b35 = va_arg(ap, bd1);
    b36 = va_arg(ap, bd2);
    QUEST_ASSERT(b24 == b34);
    QUEST_ASSERT(b25 == b35);
    QUEST_ASSERT(b26.b2 == b36.b2);
    va_end(ap);
    return b23;
}
static void caller_b1f()
{
    struct bt7 b37; 
    /* seed: 824 */
    b37 = callee_b0f(b27, b28, b29, b30, b31, b32, b33, b24, b25, b26);
    QUEST_ASSERT(b23.b20 == b37.b20);
    QUEST_ASSERT(b23.b21.b12 == b37.b21.b12);
    QUEST_ASSERT(b23.b21.b13 == b37.b21.b13);
    QUEST_ASSERT(b23.b21.b14 == b37.b21.b14);
    QUEST_ASSERT(b23.b21.b15 == b37.b21.b15);
    QUEST_ASSERT(b23.b21.b16 == b37.b21.b16);
    QUEST_ASSERT(b23.b22.b17 == b37.b22.b17);
}
int main(int argc, char **argv) {  caller_b1f(); return errors; }
