/* $Id: quest.lua 3 2006-04-29 13:17:19Z lindig $ */
/* ./quest.opt */

/*
 * This code is generated by Quest and is intended to find
 * inconsistencies in C compilers. To learn more about Quest, visit:
 *
 *      http://www.st.cs.uni-sb.de/~lindig/src/quest/
 */

/* These macros are defined in Lua string Quest.header, which may be
 * re-defined from the quest command line or in file quest.lua. 
 */
#ifndef QUEST_FAILED
#include <assert.h>
#define QUEST_ASSERT(x) assert(x)
#else
#define QUEST_ASSERT(x) if (!(x)) failed(__LINE__)
#endif

#include <stdarg.h>

extern int printf(char *, ...);
static int errors = 0;
static void failed(int line)
{  printf("failed in %s: %d\n", __FILE__, line); errors++; }
static
    struct ut4 { short int u6; union ut3 { float u5; } u7; float *u8; } u9
        = {21278, {50370.40}, (float *) 1977215579U};
static union ut0 { double *u0; } u10 = {(double *) 2095221249U};
static unsigned long int u11 = 1560289026UL;
static
    union ut1 { float u1; double u2; double u3; } *u12
        = (union ut1 *) 361770175U;
static double u13 = 51204.71;
static
    union ut2 { unsigned short int *u4; } u14
        = {(unsigned short int *) 1420758949U};
static double u15 = 84289.00;
static unsigned int u16 = 592459437U;
struct ut4 
callee_u0f(union ut0 up7,
    unsigned long int up8,
    union ut1 *up9,
    double up10,
    union ut2 up11,
    double up12,
    unsigned int up13)
{
    
    /* seed: 1909706750150761554 */
    QUEST_ASSERT(u10.u0 == up7.u0);
    QUEST_ASSERT(u11 == up8);
    QUEST_ASSERT(u12 == up9);
    QUEST_ASSERT(u13 == up10);
    QUEST_ASSERT(u14.u4 == up11.u4);
    QUEST_ASSERT(u15 == up12);
    QUEST_ASSERT(u16 == up13);
    return u9;
}
static void caller_u1f()
{
    struct ut4 u17; 
    /* seed: 1909706750150761554 */
    u17 = callee_u0f(u10, u11, u12, u13, u14, u15, u16);
    QUEST_ASSERT(u9.u6 == u17.u6);
    QUEST_ASSERT(u9.u7.u5 == u17.u7.u5);
    QUEST_ASSERT(u9.u8 == u17.u8);
}
static
    union tt6
    {
        union tt4 { int t12; double t13; short int t14; } t24;
        struct tt5
        {
            unsigned int t15;
            long int t16;
            long int t17;
            signed t18:2;
            signed t19:3;
            signed t20:5;
            float t21;
            long int t22;
            short int t23;
        }
        t25;
    }
    t26
        = {{1366202166}};
static double t27[2] = {96468.83, 6656.18};
static unsigned int t28 = 1989896037U;
static double t29 = 79796.24;
static union tt0 { long int t0; long int t1[1]; } t30 = {458953967L};
static int t31 = 1888551379;
static
    union tt2 { union tt1 { float t2; short int t3; } t4; } t32
        = {{32479.63}};
static
    struct tt3
    {
        float t5;
        signed t6:10;
        signed t7:6;
        signed t8:2;
        signed t9:6;
        int t10;
        char t11;
    }
    *t33
        = (struct tt3 *) 2118741059U;
union tt6 
callee_t0f(double tp7[2],
    unsigned int tp8,
    double tp9,
    union tt0 tp10,
    int tp11,
    union tt2 tp12,
    struct tt3 *tp13)
{
    
    /* seed: -3124617623218114893 */
    QUEST_ASSERT(t27[1] == tp7[1]);
    QUEST_ASSERT(t27[0] == tp7[0]);
    QUEST_ASSERT(t28 == tp8);
    QUEST_ASSERT(t29 == tp9);
    QUEST_ASSERT(t30.t0 == tp10.t0);
    QUEST_ASSERT(t31 == tp11);
    QUEST_ASSERT(t32.t4.t2 == tp12.t4.t2);
    QUEST_ASSERT(t33 == tp13);
    return t26;
}
static void caller_t1f()
{
    union tt6 t34; 
    /* seed: -3124617623218114893 */
    t34 = callee_t0f(t27, t28, t29, t30, t31, t32, t33);
    QUEST_ASSERT(t26.t24.t12 == t34.t24.t12);
}
static double s6 = 69352.64;
static unsigned short int s7 = 24774;
static float *s8[1] = {(float *) 1666291771U};
static
    union st1
    {
        unsigned long int s3;
        union st0 { unsigned short int s0; char s1; double s2; } s4;
        long int s5[1];
    }
    s9
        = {81298045UL};
static float s10[2][1] = {{80137.50}, {33639.06}};
static int s11 = 1394911726;
static unsigned int s12[1] = {451015344U};
static double s13 = 61660.97;
static float s14 = 3575.14;
static float s15 = 95208.98;
double
callee_s0f(unsigned short int sp9,
    float *sp10[1],
    union st1 sp11,
    float sp12[2][1],
    int sp13,
    unsigned int sp14[1],
    double sp15,
    float sp16,
    float sp17)
{
    
    /* seed: 4340140348168014846 */
    QUEST_ASSERT(s7 == sp9);
    QUEST_ASSERT(s8[0] == sp10[0]);
    QUEST_ASSERT(s9.s3 == sp11.s3);
    QUEST_ASSERT(s10[1][0] == sp12[1][0]);
    QUEST_ASSERT(s10[0][0] == sp12[0][0]);
    QUEST_ASSERT(s11 == sp13);
    QUEST_ASSERT(s12[0] == sp14[0]);
    QUEST_ASSERT(s13 == sp15);
    QUEST_ASSERT(s14 == sp16);
    QUEST_ASSERT(s15 == sp17);
    return s6;
}
static void caller_s1f()
{
    double s16; 
    /* seed: 4340140348168014846 */
    s16 = callee_s0f(s7, s8, s9, s10, s11, s12, s13, s14, s15);
    QUEST_ASSERT(s6 == s16);
}
static double r4 = 68716.20;
static int r5[1][1] = {{687927980}};
static
    union rt1
    { float r2; union rt0 { unsigned int r0; unsigned short int r1; } r3; }
    r6
        = {5081.00};
static double r7 = 51991.11;
static double callee_r0f(int rp3[1][1], union rt1 rp4, double rp5)
{
    
    /* seed: -4200026979099982624 */
    QUEST_ASSERT(r5[0][0] == rp3[0][0]);
    QUEST_ASSERT(r6.r2 == rp4.r2);
    QUEST_ASSERT(r7 == rp5);
    return r4;
}
static void caller_r1f()
{
    double r8; 
    /* seed: -4200026979099982624 */
    r8 = callee_r0f(r5, r6, r7);
    QUEST_ASSERT(r4 == r8);
}
static struct qt1 { short int q7; } *q8 = (struct qt1 *) 1372297126U;
static
    struct qt0
    {
        double q0[2];
        signed q1:9;
        signed q2:12;
        signed q3:3;
        char *q4;
        float q5[2];
        float *q6;
    }
    q9
        =
        {{71603.44, 82791.93},
            22,
            373,
            0,
            (char *) 16606841U,
            {53128.61, 54231.27},
            (float *) 696518537U};
struct qt1 * callee_q0f(struct qt0 qp1)
{
    
    /* seed: -772008615540648959 */
    QUEST_ASSERT(q9.q0[1] == qp1.q0[1]);
    QUEST_ASSERT(q9.q0[0] == qp1.q0[0]);
    QUEST_ASSERT(q9.q1 == qp1.q1);
    QUEST_ASSERT(q9.q2 == qp1.q2);
    QUEST_ASSERT(q9.q3 == qp1.q3);
    QUEST_ASSERT(q9.q4 == qp1.q4);
    QUEST_ASSERT(q9.q5[1] == qp1.q5[1]);
    QUEST_ASSERT(q9.q5[0] == qp1.q5[0]);
    QUEST_ASSERT(q9.q6 == qp1.q6);
    return q8;
}
static void caller_q1f()
{
    struct qt1 *q10; 
    /* seed: -772008615540648959 */
    q10 = callee_q0f(q9);
    QUEST_ASSERT(q8 == q10);
}
static
    struct pt7 { float p16; short int p17; } *p18
        = (struct pt7 *) 1699817446U;
static union pt0 { long int p0; float *p1; long int p2; } p19 = {445968694L};
static float *p20 = (float *) 2143845986U;
static unsigned int p21[1][1] = {{2091041083U}};
static
    union pt2
    { double p6; union pt1 { float p3; long int p4; float p5; } p7; }
    p22
        = {42080.38};
static int p23 = 1743425470;
static char p24 = '\x74';
static
    union pt4 { float p9; union pt3 { long int p8; } p10; } p25 = {21756.16};
static union pt5 { float p11; float p12; } *p26 = (union pt5 *) 1476481241U;
static union pt6 { long int p13; char p14; int p15; } p27[1] = {{374040710L}};
struct pt7 *
callee_p0f(union pt0 pp9,
    float *pp10,
    unsigned int pp11[1][1],
    union pt2 pp12,
    int pp13,
    char pp14,
    union pt4 pp15,
    union pt5 *pp16,
    union pt6 pp17[1])
{
    
    /* seed: 2912095425912030737 */
    QUEST_ASSERT(p19.p0 == pp9.p0);
    QUEST_ASSERT(p20 == pp10);
    QUEST_ASSERT(p21[0][0] == pp11[0][0]);
    QUEST_ASSERT(p22.p6 == pp12.p6);
    QUEST_ASSERT(p23 == pp13);
    QUEST_ASSERT(p24 == pp14);
    QUEST_ASSERT(p25.p9 == pp15.p9);
    QUEST_ASSERT(p26 == pp16);
    QUEST_ASSERT(p27[0].p13 == pp17[0].p13);
    return p18;
}
static void caller_p1f()
{
    struct pt7 *p28; 
    /* seed: 2912095425912030737 */
    p28 = callee_p0f(p19, p20, p21, p22, p23, p24, p25, p26, p27);
    QUEST_ASSERT(p18 == p28);
}
static unsigned char *o20 = (unsigned char *) 292131091U;
static unsigned short int o25 = 41231;
static
    struct ot3
    {
        int o6;
        union ot1 { float o2; unsigned short int o3; } o7;
        int o8[1];
        signed o9:9;
        signed o10:11;
        signed o11:9;
        signed o12:6;
        union ot2 { short int o4; unsigned int o5; } o13;
        short int o14[1];
    }
    o26
        =
        {1868018965,
            {13915.36},
            {458614973},
            201,
            519,
            42,
            28,
            {2062},
            {22845}};
static double o27 = 69048.01;
static float o28 = 44072.58;
static
    union ot6
    {
        union ot4 { unsigned long int o15; float o16; } o18;
        union ot5 { unsigned int o17; } o19;
    }
    o29
        = {{1859977578UL}};
static int o21 = 403744945;
static double o22 = 20676.30;
static
    struct ot0 { float o0[2]; double *o1; } o23
        = {{95923.44, 43394.35}, (double *) 1982067607U};
static long long int o24 = 806128427L;
unsigned char *
callee_o0f(unsigned short int op5,
    struct ot3 op6,
    double op7,
    float op8,
    union ot6 op9,
    ...)
{
    va_list ap;
    typedef int od0;
    typedef double od1;
    typedef struct ot0 od2;
    typedef long long int od3;
    od0 o30;
    od1 o31;
    od2 o32;
    od3 o33;
    
    /* seed: -422988097073143204 */
    va_start(ap, op9);
    QUEST_ASSERT(o25 == op5);
    QUEST_ASSERT(o26.o6 == op6.o6);
    QUEST_ASSERT(o26.o7.o2 == op6.o7.o2);
    QUEST_ASSERT(o26.o8[0] == op6.o8[0]);
    QUEST_ASSERT(o26.o9 == op6.o9);
    QUEST_ASSERT(o26.o10 == op6.o10);
    QUEST_ASSERT(o26.o11 == op6.o11);
    QUEST_ASSERT(o26.o12 == op6.o12);
    QUEST_ASSERT(o26.o13.o4 == op6.o13.o4);
    QUEST_ASSERT(o26.o14[0] == op6.o14[0]);
    QUEST_ASSERT(o27 == op7);
    QUEST_ASSERT(o28 == op8);
    QUEST_ASSERT(o29.o18.o15 == op9.o18.o15);
    o30 = va_arg(ap, od0);
    o31 = va_arg(ap, od1);
    o32 = va_arg(ap, od2);
    o33 = va_arg(ap, od3);
    QUEST_ASSERT(o21 == o30);
    QUEST_ASSERT(o22 == o31);
    QUEST_ASSERT(o23.o0[1] == o32.o0[1]);
    QUEST_ASSERT(o23.o0[0] == o32.o0[0]);
    QUEST_ASSERT(o23.o1 == o32.o1);
    QUEST_ASSERT(o24 == o33);
    va_end(ap);
    return o20;
}
static void caller_o1f()
{
    unsigned char *o34; 
    /* seed: -422988097073143204 */
    o34 = callee_o0f(o25, o26, o27, o28, o29, o21, o22, o23, o24);
    QUEST_ASSERT(o20 == o34);
}
static float n6 = 2417.96;
static float n7 = 7031.74;
static
    union nt1
    {
        struct nt0
        {
            unsigned char n0;
            signed n1:3;
            float n2;
            long int n3;
            unsigned char n4;
        }
        n5;
    }
    n8
        = {{'\x9', 0, 83564.76, 524036050L, '\x0'}};
float callee_n0f(float np2, union nt1 np3)
{
    
    /* seed: 148893803494178375 */
    QUEST_ASSERT(n7 == np2);
    QUEST_ASSERT(n8.n5.n0 == np3.n5.n0);
    QUEST_ASSERT(n8.n5.n1 == np3.n5.n1);
    QUEST_ASSERT(n8.n5.n2 == np3.n5.n2);
    QUEST_ASSERT(n8.n5.n3 == np3.n5.n3);
    QUEST_ASSERT(n8.n5.n4 == np3.n5.n4);
    return n6;
}
static void caller_n1f()
{
    float n9; 
    /* seed: 148893803494178375 */
    n9 = callee_n0f(n7, n8);
    QUEST_ASSERT(n6 == n9);
}
static struct mt6 { short int *m10; } m11 = {(short int *) 1886840007U};
static union mt1 { unsigned long int m3; } m14 = {1291103082UL};
static char *m15 = (char *) 1096318048U;
static
    union mt3
    { union mt2 { float m4; } m5; unsigned long int m6; float m7; }
    m16
        = {{20706.16}};
static union mt4 { short int m8; } *m17 = (union mt4 *) 24831925U;
static union mt5 { double m9; } *m18 = (union mt5 *) 742121826U;
static float m19 = 86850.99;
static char m20 = '\x20';
static float *m21 = (float *) 655093089U;
static unsigned char m22 = '\x8';
static double m12 = 10445.31;
static
    union mt0 { double *m0; short int m1; double *m2; } m13
        = {(double *) 1523407204U};
struct mt6 
callee_m0f(union mt1 mp9,
    char *mp10,
    union mt3 mp11,
    union mt4 *mp12,
    union mt5 *mp13,
    float mp14,
    char mp15,
    float *mp16,
    unsigned char mp17,
    ...)
{
    va_list ap; typedef double md0; typedef union mt0 md1; md0 m23; md1 m24; 
    /* seed: -1613962689340248185 */
    va_start(ap, mp17);
    QUEST_ASSERT(m14.m3 == mp9.m3);
    QUEST_ASSERT(m15 == mp10);
    QUEST_ASSERT(m16.m5.m4 == mp11.m5.m4);
    QUEST_ASSERT(m17 == mp12);
    QUEST_ASSERT(m18 == mp13);
    QUEST_ASSERT(m19 == mp14);
    QUEST_ASSERT(m20 == mp15);
    QUEST_ASSERT(m21 == mp16);
    QUEST_ASSERT(m22 == mp17);
    m23 = va_arg(ap, md0);
    m24 = va_arg(ap, md1);
    QUEST_ASSERT(m12 == m23);
    QUEST_ASSERT(m13.m0 == m24.m0);
    va_end(ap);
    return m11;
}
static void caller_m1f()
{
    struct mt6 m25; 
    /* seed: -1613962689340248185 */
    m25 = callee_m0f(m14, m15, m16, m17, m18, m19, m20, m21, m22, m12, m13);
    QUEST_ASSERT(m11.m10 == m25.m10);
}
static
    struct lt5
    {
        long int l16;
        struct lt4
        {
            char l10;
            double l11;
            double l12;
            signed l13:7;
            double l14;
            float l15;
        }
        l17;
    }
    l18
        = {1537567563L, {'\x56', 4271.09, 78203.15, 48, 81331.51, 33493.62}};
static union lt0 { float *l0; } l23 = {(float *) 15088857U};
static
    struct lt1
    { float l1; signed l2:3; signed l3:8; signed l4:8; signed l5:7; int l6; }
    *l24
        = (struct lt1 *) 1948776261U;
static float l25[2] = {55371.48, 11178.66};
static char l26 = '\x25';
static float l27 = 75217.28;
static float l28 = 1482.46;
static double l29 = 2257.01;
static double l30 = 87121.83;
static union lt2 { float l7; double l8; } l31[2] = {{55419.26}, {52345.78}};
static union lt3 { double l9; } l32 = {76582.51};
static int l19 = 1898862297;
static int l20 = 1844754841;
static int l21 = 1467849659;
static int **l22 = (int **) 775479361U;
static
struct lt5 
callee_l0f(union lt0 lp10,
    struct lt1 *lp11,
    float lp12[2],
    char lp13,
    float lp14,
    float lp15,
    double lp16,
    double lp17,
    union lt2 lp18[2],
    union lt3 lp19,
    ...)
{
    va_list ap;
    typedef int ld0;
    typedef int ld1;
    typedef int ld2;
    typedef int **ld3;
    ld0 l33;
    ld1 l34;
    ld2 l35;
    ld3 l36;
    
    /* seed: -4105422139343391270 */
    va_start(ap, lp19);
    QUEST_ASSERT(l23.l0 == lp10.l0);
    QUEST_ASSERT(l24 == lp11);
    QUEST_ASSERT(l25[1] == lp12[1]);
    QUEST_ASSERT(l25[0] == lp12[0]);
    QUEST_ASSERT(l26 == lp13);
    QUEST_ASSERT(l27 == lp14);
    QUEST_ASSERT(l28 == lp15);
    QUEST_ASSERT(l29 == lp16);
    QUEST_ASSERT(l30 == lp17);
    QUEST_ASSERT(l31[1].l7 == lp18[1].l7);
    QUEST_ASSERT(l31[0].l7 == lp18[0].l7);
    QUEST_ASSERT(l32.l9 == lp19.l9);
    l33 = va_arg(ap, ld0);
    l34 = va_arg(ap, ld1);
    l35 = va_arg(ap, ld2);
    l36 = va_arg(ap, ld3);
    QUEST_ASSERT(l19 == l33);
    QUEST_ASSERT(l20 == l34);
    QUEST_ASSERT(l21 == l35);
    QUEST_ASSERT(l22 == l36);
    va_end(ap);
    return l18;
}
static void caller_l1f()
{
    struct lt5 l37; 
    /* seed: -4105422139343391270 */
    l37
    =
    callee_l0f(l23,
            l24,
            l25,
            l26,
            l27,
            l28,
            l29,
            l30,
            l31,
            l32,
            l19,
            l20,
            l21,
            l22);
    QUEST_ASSERT(l18.l16 == l37.l16);
    QUEST_ASSERT(l18.l17.l10 == l37.l17.l10);
    QUEST_ASSERT(l18.l17.l11 == l37.l17.l11);
    QUEST_ASSERT(l18.l17.l12 == l37.l17.l12);
    QUEST_ASSERT(l18.l17.l13 == l37.l17.l13);
    QUEST_ASSERT(l18.l17.l14 == l37.l17.l14);
    QUEST_ASSERT(l18.l17.l15 == l37.l17.l15);
}
static unsigned int *k28 = (unsigned int *) 425672899U;
static
    struct kt3
    {
        double k10[2];
        double *k11;
        float *k12;
        union kt2 { double k8; float k9; } k13;
        float k14[1];
        char *k15;
    }
    k32
        =
        {{63157.46, 90549.13},
            (double *) 945943030U,
            (float *) 506096111U,
            {39084.64},
            {66386.60},
            (char *) 1239541789U};
static union kt4 { double k16; double *k17; } k33 = {83100.84};
static double k34 = 54426.14;
static
    struct kt6
    {
        unsigned long int k20;
        struct kt5 { double k18; unsigned int k19; } k21;
        short int k22[1];
        signed k23:10;
        signed k24:2;
        unsigned int k25;
        double k26;
        double k27[1];
    }
    k35
        =
        {795511133UL,
            {98880.34, 2092046316U},
            {18365},
            424,
            1,
            515623718U,
            50243.40,
            {24982.83}};
static int *k29[1] = {(int *) 1234211575U};
static long int k30[1] = {1812909727L};
static
    union kt1
    {
        struct kt0
        {
            float k0;
            double k1;
            double k2;
            signed k3:12;
            char k4;
            unsigned char k5;
        }
        k6;
        float *k7;
    }
    k31
        = {{98188.92, 62616.40, 29133.25, 1997, '\x6f', '\x1a'}};
static
unsigned int *
callee_k0f(struct kt3 kp4, union kt4 kp5, double kp6, struct kt6 kp7, ...)
{
    va_list ap;
    typedef int **kd0;
    typedef long int *kd1;
    typedef union kt1 kd2;
    kd0 k36;
    kd1 k37;
    kd2 k38;
    
    /* seed: -1814545954907185616 */
    va_start(ap, kp7);
    QUEST_ASSERT(k32.k10[1] == kp4.k10[1]);
    QUEST_ASSERT(k32.k10[0] == kp4.k10[0]);
    QUEST_ASSERT(k32.k11 == kp4.k11);
    QUEST_ASSERT(k32.k12 == kp4.k12);
    QUEST_ASSERT(k32.k13.k8 == kp4.k13.k8);
    QUEST_ASSERT(k32.k14[0] == kp4.k14[0]);
    QUEST_ASSERT(k32.k15 == kp4.k15);
    QUEST_ASSERT(k33.k16 == kp5.k16);
    QUEST_ASSERT(k34 == kp6);
    QUEST_ASSERT(k35.k20 == kp7.k20);
    QUEST_ASSERT(k35.k21.k18 == kp7.k21.k18);
    QUEST_ASSERT(k35.k21.k19 == kp7.k21.k19);
    QUEST_ASSERT(k35.k22[0] == kp7.k22[0]);
    QUEST_ASSERT(k35.k23 == kp7.k23);
    QUEST_ASSERT(k35.k24 == kp7.k24);
    QUEST_ASSERT(k35.k25 == kp7.k25);
    QUEST_ASSERT(k35.k26 == kp7.k26);
    QUEST_ASSERT(k35.k27[0] == kp7.k27[0]);
    k36 = va_arg(ap, kd0);
    k37 = va_arg(ap, kd1);
    k38 = va_arg(ap, kd2);
    QUEST_ASSERT(k29[0] == k36[0]);
    QUEST_ASSERT(k30[0] == k37[0]);
    QUEST_ASSERT(k31.k6.k0 == k38.k6.k0);
    QUEST_ASSERT(k31.k6.k1 == k38.k6.k1);
    QUEST_ASSERT(k31.k6.k2 == k38.k6.k2);
    QUEST_ASSERT(k31.k6.k3 == k38.k6.k3);
    QUEST_ASSERT(k31.k6.k4 == k38.k6.k4);
    QUEST_ASSERT(k31.k6.k5 == k38.k6.k5);
    va_end(ap);
    return k28;
}
static void caller_k1f()
{
    unsigned int *k39; 
    /* seed: -1814545954907185616 */
    k39 = callee_k0f(k32, k33, k34, k35, k29, k30, k31);
    QUEST_ASSERT(k28 == k39);
}
static long int *j65 = (long int *) 1727646810U;
static
    union jt1 { double j2; unsigned int j3; } *j68
        = (union jt1 *) 1263275091U;
static union jt2 { short int *j4; } j69 = {(short int *) 619543306U};
static
    struct jt4
    {
        double j6;
        union jt3 { short int j5; } j7;
        double j8[2];
        signed j9:6;
        signed j10:7;
        signed j11:11;
        signed j12:4;
        float *j13;
    }
    j70
        =
        {51320.68,
            {3952},
            {19770.88, 64003.22},
            3,
            43,
            971,
            6,
            (float *) 982543102U};
static long int j71 = 768760594L;
static
    struct jt7
    {
        union jt5 { int j14; double j15; } j18;
        union jt6 { long int j16; double j17; } j19;
        short int *j20;
        signed j21:6;
        signed j22:10;
        signed j23:5;
        signed j24:2;
        double j25;
        double j26[1];
        unsigned int j27;
    }
    j72
        =
        {{1482494860},
            {304519575L},
            (short int *) 375556U,
            30,
            349,
            14,
            1,
            3473.56,
            {54884.73},
            2051005765U};
static
    union jt8 { unsigned int j28; float j29; double j30; } *j73
        = (union jt8 *) 802178432U;
static union jt9 { double *j31; float *j32; } j74 = {(double *) 1589044843U};
static
    struct jt12
    {
        double *j50;
        signed j51:7;
        signed j52:3;
        signed j53:10;
        signed j54:8;
        struct jt10
        {
            char j33;
            double j34;
            float j35;
            signed j36:9;
            signed j37:12;
            unsigned char j38;
            long int j39;
            double j40;
        }
        j55;
        struct jt11
        {
            float j41;
            float j42;
            signed j43:12;
            signed j44:7;
            signed j45:7;
            signed j46:6;
            double j47;
            float j48;
            double j49;
        }
        j56;
        char j57;
    }
    j75
        =
        {(double *) 1549082009U,
            15,
            2,
            429,
            62,
            {'\x25',
                14909.93,
                7516.03,
                46,
                405,
                '\x50',
                300345042L,
                74248.52},
            {32210.09, 905.64, 851, 15, 39, 12, 14096.67, 34433.70, 35775.96},
            '\x70'};
static short int *j76 = (short int *) 1418858771U;
static
    union jt15
    {
        union jt13 { double j58; float j59; int j60; } j62;
        union jt14 { unsigned char j61; } j63;
        double j64[1];
    }
    j77
        = {{27968.70}};
static struct jt0 { float j0[1]; float j1; } j66 = {{98917.79}, 5612.78};
static int j67 = 733264477;
long int *
callee_j0f(union jt1 *jp10,
    union jt2 jp11,
    struct jt4 jp12,
    long int jp13,
    struct jt7 jp14,
    union jt8 *jp15,
    union jt9 jp16,
    struct jt12 jp17,
    short int *jp18,
    union jt15 jp19,
    ...)
{
    va_list ap; typedef struct jt0 jd0; typedef int jd1; jd0 j78; jd1 j79; 
    /* seed: -1205113938487003262 */
    va_start(ap, jp19);
    QUEST_ASSERT(j68 == jp10);
    QUEST_ASSERT(j69.j4 == jp11.j4);
    QUEST_ASSERT(j70.j6 == jp12.j6);
    QUEST_ASSERT(j70.j7.j5 == jp12.j7.j5);
    QUEST_ASSERT(j70.j8[1] == jp12.j8[1]);
    QUEST_ASSERT(j70.j8[0] == jp12.j8[0]);
    QUEST_ASSERT(j70.j9 == jp12.j9);
    QUEST_ASSERT(j70.j10 == jp12.j10);
    QUEST_ASSERT(j70.j11 == jp12.j11);
    QUEST_ASSERT(j70.j12 == jp12.j12);
    QUEST_ASSERT(j70.j13 == jp12.j13);
    QUEST_ASSERT(j71 == jp13);
    QUEST_ASSERT(j72.j18.j14 == jp14.j18.j14);
    QUEST_ASSERT(j72.j19.j16 == jp14.j19.j16);
    QUEST_ASSERT(j72.j20 == jp14.j20);
    QUEST_ASSERT(j72.j21 == jp14.j21);
    QUEST_ASSERT(j72.j22 == jp14.j22);
    QUEST_ASSERT(j72.j23 == jp14.j23);
    QUEST_ASSERT(j72.j24 == jp14.j24);
    QUEST_ASSERT(j72.j25 == jp14.j25);
    QUEST_ASSERT(j72.j26[0] == jp14.j26[0]);
    QUEST_ASSERT(j72.j27 == jp14.j27);
    QUEST_ASSERT(j73 == jp15);
    QUEST_ASSERT(j74.j31 == jp16.j31);
    QUEST_ASSERT(j75.j50 == jp17.j50);
    QUEST_ASSERT(j75.j51 == jp17.j51);
    QUEST_ASSERT(j75.j52 == jp17.j52);
    QUEST_ASSERT(j75.j53 == jp17.j53);
    QUEST_ASSERT(j75.j54 == jp17.j54);
    QUEST_ASSERT(j75.j55.j33 == jp17.j55.j33);
    QUEST_ASSERT(j75.j55.j34 == jp17.j55.j34);
    QUEST_ASSERT(j75.j55.j35 == jp17.j55.j35);
    QUEST_ASSERT(j75.j55.j36 == jp17.j55.j36);
    QUEST_ASSERT(j75.j55.j37 == jp17.j55.j37);
    QUEST_ASSERT(j75.j55.j38 == jp17.j55.j38);
    QUEST_ASSERT(j75.j55.j39 == jp17.j55.j39);
    QUEST_ASSERT(j75.j55.j40 == jp17.j55.j40);
    QUEST_ASSERT(j75.j56.j41 == jp17.j56.j41);
    QUEST_ASSERT(j75.j56.j42 == jp17.j56.j42);
    QUEST_ASSERT(j75.j56.j43 == jp17.j56.j43);
    QUEST_ASSERT(j75.j56.j44 == jp17.j56.j44);
    QUEST_ASSERT(j75.j56.j45 == jp17.j56.j45);
    QUEST_ASSERT(j75.j56.j46 == jp17.j56.j46);
    QUEST_ASSERT(j75.j56.j47 == jp17.j56.j47);
    QUEST_ASSERT(j75.j56.j48 == jp17.j56.j48);
    QUEST_ASSERT(j75.j56.j49 == jp17.j56.j49);
    QUEST_ASSERT(j75.j57 == jp17.j57);
    QUEST_ASSERT(j76 == jp18);
    QUEST_ASSERT(j77.j62.j58 == jp19.j62.j58);
    j78 = va_arg(ap, jd0);
    j79 = va_arg(ap, jd1);
    QUEST_ASSERT(j66.j0[0] == j78.j0[0]);
    QUEST_ASSERT(j66.j1 == j78.j1);
    QUEST_ASSERT(j67 == j79);
    va_end(ap);
    return j65;
}
static void caller_j1f()
{
    long int *j80; 
    /* seed: -1205113938487003262 */
    j80
    =
    callee_j0f(j68, j69, j70, j71, j72, j73, j74, j75, j76, j77, j66, j67);
    QUEST_ASSERT(j65 == j80);
}
static unsigned long int i8 = 1766633645UL;
static float i12[1][1] = {{75266.63}};
static long long int i9 = 1946633575L;
static double i10 = 41960.56;
static
    struct it1
    {
        float *i5;
        struct it0
        { char i0; double i1; float i2; signed i3:3; double i4; }
        i6;
        int *i7;
    }
    i11
        =
        {(float *) 357720625U,
            {'\x5', 8907.10, 80266.29, 2, 93649.23},
            (int *) 847805979U};
unsigned long int callee_i0f(float ip1[1][1], ...)
{
    va_list ap;
    typedef long long int id0;
    typedef double id1;
    typedef struct it1 id2;
    id0 i13;
    id1 i14;
    id2 i15;
    
    /* seed: 2001397110937755664 */
    va_start(ap, ip1);
    QUEST_ASSERT(i12[0][0] == ip1[0][0]);
    i13 = va_arg(ap, id0);
    i14 = va_arg(ap, id1);
    i15 = va_arg(ap, id2);
    QUEST_ASSERT(i9 == i13);
    QUEST_ASSERT(i10 == i14);
    QUEST_ASSERT(i11.i5 == i15.i5);
    QUEST_ASSERT(i11.i6.i0 == i15.i6.i0);
    QUEST_ASSERT(i11.i6.i1 == i15.i6.i1);
    QUEST_ASSERT(i11.i6.i2 == i15.i6.i2);
    QUEST_ASSERT(i11.i6.i3 == i15.i6.i3);
    QUEST_ASSERT(i11.i6.i4 == i15.i6.i4);
    QUEST_ASSERT(i11.i7 == i15.i7);
    va_end(ap);
    return i8;
}
static void caller_i1f()
{
    unsigned long int i16; 
    /* seed: 2001397110937755664 */
    i16 = callee_i0f(i12, i9, i10, i11);
    QUEST_ASSERT(i8 == i16);
}
static double *h40 = (double *) 867357082U;
static
    union ht0
    { unsigned short int h0; unsigned short int h1; double h2; }
    *h43
        = (union ht0 *) 340885543U;
static
    struct ht1
    {
        double h3;
        short int h4;
        unsigned short int h5;
        signed h6:3;
        signed h7:10;
        signed h8:10;
        signed h9:11;
        char h10;
    }
    *h44
        = (struct ht1 *) 1630188192U;
static union ht2 { unsigned int h11; } h45 = {687478858U};
static
    union ht4 { union ht3 { double h12; double h13; } h14; char h15; } h46
        = {{52965.24}};
static
    struct ht7
    {
        union ht5 { unsigned int h16; } h23;
        struct ht6
        {
            char h17;
            float h18;
            unsigned short int h19;
            float h20;
            float h21;
            unsigned char h22;
        }
        h24;
        unsigned int h25;
        signed h26:4;
        unsigned long int h27;
        double h28;
    }
    h47
        =
        {{1501174614U},
            {'\x51', 19972.53, 22925, 54519.76, 38619.73, '\x53'},
            2090774251U,
            4,
            1785646706UL,
            32944.69};
static float h48[2] = {56160.55, 69483.55};
static double h49[1] = {30450.78};
static
    union ht8 { unsigned long int h29[1]; float h30[2]; } h50
        = {{1708430691UL}};
static
    struct ht9
    {
        unsigned char h31;
        double h32;
        float h33;
        signed h34:7;
        signed h35:3;
        signed h36:2;
        float h37;
        unsigned char h38;
        double h39;
    }
    *h51
        = (struct ht9 *) 548451448U;
static
    unsigned short int *h52[2]
        =
        {(unsigned short int *) 1910276016U,
            (unsigned short int *) 1493954214U};
static long int h41 = 106264118L;
static long int h42 = 338748698L;
double *
callee_h0f(union ht0 *hp10,
    struct ht1 *hp11,
    union ht2 hp12,
    union ht4 hp13,
    struct ht7 hp14,
    float hp15[2],
    double hp16[1],
    union ht8 hp17,
    struct ht9 *hp18,
    unsigned short int *hp19[2],
    ...)
{
    va_list ap; typedef long int hd0; typedef long int hd1; hd0 h53; hd1 h54; 
    /* seed: -848962983543035684 */
    va_start(ap, hp19);
    QUEST_ASSERT(h43 == hp10);
    QUEST_ASSERT(h44 == hp11);
    QUEST_ASSERT(h45.h11 == hp12.h11);
    QUEST_ASSERT(h46.h14.h12 == hp13.h14.h12);
    QUEST_ASSERT(h47.h23.h16 == hp14.h23.h16);
    QUEST_ASSERT(h47.h24.h17 == hp14.h24.h17);
    QUEST_ASSERT(h47.h24.h18 == hp14.h24.h18);
    QUEST_ASSERT(h47.h24.h19 == hp14.h24.h19);
    QUEST_ASSERT(h47.h24.h20 == hp14.h24.h20);
    QUEST_ASSERT(h47.h24.h21 == hp14.h24.h21);
    QUEST_ASSERT(h47.h24.h22 == hp14.h24.h22);
    QUEST_ASSERT(h47.h25 == hp14.h25);
    QUEST_ASSERT(h47.h26 == hp14.h26);
    QUEST_ASSERT(h47.h27 == hp14.h27);
    QUEST_ASSERT(h47.h28 == hp14.h28);
    QUEST_ASSERT(h48[1] == hp15[1]);
    QUEST_ASSERT(h48[0] == hp15[0]);
    QUEST_ASSERT(h49[0] == hp16[0]);
    QUEST_ASSERT(h50.h29[0] == hp17.h29[0]);
    QUEST_ASSERT(h51 == hp18);
    QUEST_ASSERT(h52[1] == hp19[1]);
    QUEST_ASSERT(h52[0] == hp19[0]);
    h53 = va_arg(ap, hd0);
    h54 = va_arg(ap, hd1);
    QUEST_ASSERT(h41 == h53);
    QUEST_ASSERT(h42 == h54);
    va_end(ap);
    return h40;
}
static void caller_h1f()
{
    double *h55; 
    /* seed: -848962983543035684 */
    h55
    =
    callee_h0f(h43, h44, h45, h46, h47, h48, h49, h50, h51, h52, h41, h42);
    QUEST_ASSERT(h40 == h55);
}
static
    union gt8
    {
        int *g36;
        double g37;
        struct gt7
        {
            unsigned int g28;
            float g29;
            signed g30:2;
            signed g31:10;
            signed g32:2;
            signed g33:6;
            char g34;
            float g35;
        }
        g38;
    }
    g39
        = {(int *) 136808716U};
static unsigned short int g43 = 64723;
static
    union gt1 { unsigned short int *g1; } g44
        = {(unsigned short int *) 1191959860U};
static double g45 = 54261.90;
static unsigned long int *g46 = (unsigned long int *) 286809001U;
static float g47 = 63487.82;
static int g48[2] = {108155671, 1992610358};
static
    struct gt4
    {
        struct gt2
        {
            double g2;
            double g3;
            short int g4;
            signed g5:12;
            signed g6:11;
            unsigned long int g7;
            int g8;
            float g9;
        }
        g13;
        double g14[1];
        union gt3 { long int g10; double g11; float g12; } g15;
        signed g16:7;
        signed g17:7;
        signed g18:8;
        signed g19:8;
        float *g20;
        int g21;
    }
    g49
        =
        {{34551.24,
                70325.36,
                27950,
                1595,
                206,
                1939928660UL,
                560125653,
                53016.55},
            {60175.97},
            {2133560865L},
            16,
            26,
            98,
            13,
            (float *) 210181761U,
            1754192735};
static int g50 = 1117426957;
static
    struct gt6
    {
        float *g25;
        union gt5 { float g22; unsigned long int g23; char g24; } g26;
        float g27[1];
    }
    g51
        = {(float *) 261919686U, {78795.57}, {38866.46}};
static long int g40 = 472904770L;
static struct gt0 { unsigned char g0; } g41 = {'\x14'};
static int g42 = 1007681219;
union gt8 
callee_g0f(unsigned short int gp9,
    union gt1 gp10,
    double gp11,
    unsigned long int *gp12,
    float gp13,
    int gp14[2],
    struct gt4 gp15,
    int gp16,
    struct gt6 gp17,
    ...)
{
    va_list ap;
    typedef long int gd0;
    typedef struct gt0 gd1;
    typedef int gd2;
    gd0 g52;
    gd1 g53;
    gd2 g54;
    
    /* seed: -1505472465053826271 */
    va_start(ap, gp17);
    QUEST_ASSERT(g43 == gp9);
    QUEST_ASSERT(g44.g1 == gp10.g1);
    QUEST_ASSERT(g45 == gp11);
    QUEST_ASSERT(g46 == gp12);
    QUEST_ASSERT(g47 == gp13);
    QUEST_ASSERT(g48[1] == gp14[1]);
    QUEST_ASSERT(g48[0] == gp14[0]);
    QUEST_ASSERT(g49.g13.g2 == gp15.g13.g2);
    QUEST_ASSERT(g49.g13.g3 == gp15.g13.g3);
    QUEST_ASSERT(g49.g13.g4 == gp15.g13.g4);
    QUEST_ASSERT(g49.g13.g5 == gp15.g13.g5);
    QUEST_ASSERT(g49.g13.g6 == gp15.g13.g6);
    QUEST_ASSERT(g49.g13.g7 == gp15.g13.g7);
    QUEST_ASSERT(g49.g13.g8 == gp15.g13.g8);
    QUEST_ASSERT(g49.g13.g9 == gp15.g13.g9);
    QUEST_ASSERT(g49.g14[0] == gp15.g14[0]);
    QUEST_ASSERT(g49.g15.g10 == gp15.g15.g10);
    QUEST_ASSERT(g49.g16 == gp15.g16);
    QUEST_ASSERT(g49.g17 == gp15.g17);
    QUEST_ASSERT(g49.g18 == gp15.g18);
    QUEST_ASSERT(g49.g19 == gp15.g19);
    QUEST_ASSERT(g49.g20 == gp15.g20);
    QUEST_ASSERT(g49.g21 == gp15.g21);
    QUEST_ASSERT(g50 == gp16);
    QUEST_ASSERT(g51.g25 == gp17.g25);
    QUEST_ASSERT(g51.g26.g22 == gp17.g26.g22);
    QUEST_ASSERT(g51.g27[0] == gp17.g27[0]);
    g52 = va_arg(ap, gd0);
    g53 = va_arg(ap, gd1);
    g54 = va_arg(ap, gd2);
    QUEST_ASSERT(g40 == g52);
    QUEST_ASSERT(g41.g0 == g53.g0);
    QUEST_ASSERT(g42 == g54);
    va_end(ap);
    return g39;
}
static void caller_g1f()
{
    union gt8 g55; 
    /* seed: -1505472465053826271 */
    g55
    =
    callee_g0f(g43, g44, g45, g46, g47, g48, g49, g50, g51, g40, g41, g42);
    QUEST_ASSERT(g39.g36 == g55.g36);
}
static unsigned short int **f11 = (unsigned short int **) 1060337117U;
static float f16[2][1] = {{19483.47}, {18720.10}};
static int *f17 = (int *) 503001079U;
static float f18[1] = {70199.70};
static float *f19 = (float *) 966273425U;
static double f20 = 95068.40;
static double f21 = 54269.25;
static
    struct ft2
    {
        struct ft0 { float f0; double f1; } f5;
        signed f6:8;
        struct ft1 { char f2; double f3; float f4; } f7;
        unsigned long int *f8;
    }
    f22
        =
        {{70681.17, 75207.86},
            68,
            {'\x6c', 59844.69, 87647.74},
            (unsigned long int *) 361306956U};
static union ft3 { double f9; double f10; } *f23 = (union ft3 *) 1161477611U;
static float f12[1] = {80600.90};
static long long int f13 = 1521889599L;
static int f14 = 1412061597;
static long int f15 = 1269442414L;
static
unsigned short int **
callee_f0f(float fp8[2][1],
    int *fp9,
    float fp10[1],
    float *fp11,
    double fp12,
    double fp13,
    struct ft2 fp14,
    union ft3 *fp15,
    ...)
{
    va_list ap;
    typedef float *fd0;
    typedef long long int fd1;
    typedef int fd2;
    typedef long int fd3;
    fd0 f24;
    fd1 f25;
    fd2 f26;
    fd3 f27;
    
    /* seed: -4547911695491229367 */
    va_start(ap, fp15);
    QUEST_ASSERT(f16[1][0] == fp8[1][0]);
    QUEST_ASSERT(f16[0][0] == fp8[0][0]);
    QUEST_ASSERT(f17 == fp9);
    QUEST_ASSERT(f18[0] == fp10[0]);
    QUEST_ASSERT(f19 == fp11);
    QUEST_ASSERT(f20 == fp12);
    QUEST_ASSERT(f21 == fp13);
    QUEST_ASSERT(f22.f5.f0 == fp14.f5.f0);
    QUEST_ASSERT(f22.f5.f1 == fp14.f5.f1);
    QUEST_ASSERT(f22.f6 == fp14.f6);
    QUEST_ASSERT(f22.f7.f2 == fp14.f7.f2);
    QUEST_ASSERT(f22.f7.f3 == fp14.f7.f3);
    QUEST_ASSERT(f22.f7.f4 == fp14.f7.f4);
    QUEST_ASSERT(f22.f8 == fp14.f8);
    QUEST_ASSERT(f23 == fp15);
    f24 = va_arg(ap, fd0);
    f25 = va_arg(ap, fd1);
    f26 = va_arg(ap, fd2);
    f27 = va_arg(ap, fd3);
    QUEST_ASSERT(f12[0] == f24[0]);
    QUEST_ASSERT(f13 == f25);
    QUEST_ASSERT(f14 == f26);
    QUEST_ASSERT(f15 == f27);
    va_end(ap);
    return f11;
}
static void caller_f1f()
{
    unsigned short int **f28; 
    /* seed: -4547911695491229367 */
    f28
    =
    callee_f0f(f16, f17, f18, f19, f20, f21, f22, f23, f12, f13, f14, f15);
    QUEST_ASSERT(f11 == f28);
}
static float e24 = 33160.67;
static int e25 = 1643345042;
static unsigned char e26 = '\x34';
static
    struct et0
    {
        int e0;
        float e1;
        signed e2:12;
        signed e3:11;
        signed e4:9;
        signed e5:12;
        int e6;
        float e7;
        double e8;
    }
    *e27
        = (struct et0 *) 1206399807U;
static
    struct et2
    {
        float *e15;
        float e16;
        long int e17;
        struct et1
        {
            char e9;
            signed e10:8;
            signed e11:8;
            float e12;
            double e13;
            unsigned char e14;
        }
        e18;
    }
    e28
        =
        {(float *) 1341099585U,
            89992.01,
            1609033168L,
            {'\x5c', 88, 93, 64270.68, 86658.06, '\x5e'}};
static
    struct et3
    {
        int e19;
        char e20;
        unsigned short int e21;
        signed e22:8;
        unsigned int e23;
    }
    *e29
        = (struct et3 *) 1654739083U;
float
callee_e0f(int ep5,
    unsigned char ep6,
    struct et0 *ep7,
    struct et2 ep8,
    struct et3 *ep9)
{
    
    /* seed: 4407724058035941319 */
    QUEST_ASSERT(e25 == ep5);
    QUEST_ASSERT(e26 == ep6);
    QUEST_ASSERT(e27 == ep7);
    QUEST_ASSERT(e28.e15 == ep8.e15);
    QUEST_ASSERT(e28.e16 == ep8.e16);
    QUEST_ASSERT(e28.e17 == ep8.e17);
    QUEST_ASSERT(e28.e18.e9 == ep8.e18.e9);
    QUEST_ASSERT(e28.e18.e10 == ep8.e18.e10);
    QUEST_ASSERT(e28.e18.e11 == ep8.e18.e11);
    QUEST_ASSERT(e28.e18.e12 == ep8.e18.e12);
    QUEST_ASSERT(e28.e18.e13 == ep8.e18.e13);
    QUEST_ASSERT(e28.e18.e14 == ep8.e18.e14);
    QUEST_ASSERT(e29 == ep9);
    return e24;
}
static void caller_e1f()
{
    float e30; 
    /* seed: 4407724058035941319 */
    e30 = callee_e0f(e25, e26, e27, e28, e29);
    QUEST_ASSERT(e24 == e30);
}
static
    struct dt14 { unsigned char d46[1]; double d47; float d48; } d49
        = {{'\x1b'}, 54144.93, 30914.47};
static
    struct dt3
    {
        struct dt0
        {
            unsigned short int d0;
            char d1;
            double d2;
            unsigned int d3;
            char d4;
        }
        d11;
        union dt1 { long int d5; unsigned long int d6; } d12;
        unsigned char d13;
        struct dt2 { double d7; double d8; signed d9:7; float d10; } d14;
        float *d15;
    }
    d53
        =
        {{16998, '\x45', 77487.34, 525956274U, '\x31'},
            {1738003738L},
            '\x5d',
            {23261.51, 38066.09, 55, 45850.39},
            (float *) 1896178138U};
static union dt4 { double d16; double d17; } *d54 = (union dt4 *) 1427873921U;
static union dt5 { int d18; double d19; char d20; } d55[1] = {{2062132954}};
static
    union dt6 { double d21; float d22; float d23; } *d56
        = (union dt6 *) 1705706563U;
static
    union dt8
    {
        double d26;
        int d27;
        union dt7 { unsigned char d24; unsigned short int d25; } d28;
    }
    d57
        = {60745.73};
static
    union dt9 { unsigned short int d29; unsigned short int d30; } *d58
        = (union dt9 *) 1789899044U;
static
    struct dt11
    {
        long int d32[1];
        signed d33:5;
        signed d34:2;
        signed d35:9;
        signed d36:8;
        union dt10 { float d31; } d37;
        double d38;
    }
    d59
        = {{1676560814L}, 12, 0, 0, 91, {99999.21}, 73517.12};
static
    struct dt12 { char d39[1]; unsigned short int d40; } d60
        = {{'\x60'}, 12247};
static unsigned long int d61 = 587462401UL;
static
    struct dt13
    {
        unsigned char d41;
        signed d42:8;
        signed d43:2;
        long int d44[1];
        float *d45;
    }
    d62
        = {'\x6f', 15, 1, {822790782L}, (float *) 80636123U};
static double d50 = 24499.18;
static int d51 = 1158268627;
static long int d52 = 1046571423L;
struct dt14 
callee_d0f(struct dt3 dp10,
    union dt4 *dp11,
    union dt5 dp12[1],
    union dt6 *dp13,
    union dt8 dp14,
    union dt9 *dp15,
    struct dt11 dp16,
    struct dt12 dp17,
    unsigned long int dp18,
    struct dt13 dp19,
    ...)
{
    va_list ap;
    typedef double dd0;
    typedef int dd1;
    typedef long int dd2;
    dd0 d63;
    dd1 d64;
    dd2 d65;
    
    /* seed: -1371212341735182961 */
    va_start(ap, dp19);
    QUEST_ASSERT(d53.d11.d0 == dp10.d11.d0);
    QUEST_ASSERT(d53.d11.d1 == dp10.d11.d1);
    QUEST_ASSERT(d53.d11.d2 == dp10.d11.d2);
    QUEST_ASSERT(d53.d11.d3 == dp10.d11.d3);
    QUEST_ASSERT(d53.d11.d4 == dp10.d11.d4);
    QUEST_ASSERT(d53.d12.d5 == dp10.d12.d5);
    QUEST_ASSERT(d53.d13 == dp10.d13);
    QUEST_ASSERT(d53.d14.d7 == dp10.d14.d7);
    QUEST_ASSERT(d53.d14.d8 == dp10.d14.d8);
    QUEST_ASSERT(d53.d14.d9 == dp10.d14.d9);
    QUEST_ASSERT(d53.d14.d10 == dp10.d14.d10);
    QUEST_ASSERT(d53.d15 == dp10.d15);
    QUEST_ASSERT(d54 == dp11);
    QUEST_ASSERT(d55[0].d18 == dp12[0].d18);
    QUEST_ASSERT(d56 == dp13);
    QUEST_ASSERT(d57.d26 == dp14.d26);
    QUEST_ASSERT(d58 == dp15);
    QUEST_ASSERT(d59.d32[0] == dp16.d32[0]);
    QUEST_ASSERT(d59.d33 == dp16.d33);
    QUEST_ASSERT(d59.d34 == dp16.d34);
    QUEST_ASSERT(d59.d35 == dp16.d35);
    QUEST_ASSERT(d59.d36 == dp16.d36);
    QUEST_ASSERT(d59.d37.d31 == dp16.d37.d31);
    QUEST_ASSERT(d59.d38 == dp16.d38);
    QUEST_ASSERT(d60.d39[0] == dp17.d39[0]);
    QUEST_ASSERT(d60.d40 == dp17.d40);
    QUEST_ASSERT(d61 == dp18);
    QUEST_ASSERT(d62.d41 == dp19.d41);
    QUEST_ASSERT(d62.d42 == dp19.d42);
    QUEST_ASSERT(d62.d43 == dp19.d43);
    QUEST_ASSERT(d62.d44[0] == dp19.d44[0]);
    QUEST_ASSERT(d62.d45 == dp19.d45);
    d63 = va_arg(ap, dd0);
    d64 = va_arg(ap, dd1);
    d65 = va_arg(ap, dd2);
    QUEST_ASSERT(d50 == d63);
    QUEST_ASSERT(d51 == d64);
    QUEST_ASSERT(d52 == d65);
    va_end(ap);
    return d49;
}
static void caller_d1f()
{
    struct dt14 d66; 
    /* seed: -1371212341735182961 */
    d66
    =
    callee_d0f(d53,
            d54,
            d55,
            d56,
            d57,
            d58,
            d59,
            d60,
            d61,
            d62,
            d50,
            d51,
            d52);
    QUEST_ASSERT(d49.d46[0] == d66.d46[0]);
    QUEST_ASSERT(d49.d47 == d66.d47);
    QUEST_ASSERT(d49.d48 == d66.d48);
}
static float *c36 = (float *) 1053581012U;
static
    union ct3
    {
        union ct0 { float c0; unsigned long int c1; } c11;
        union ct1 { double c2; short int c3; } c12;
        struct ct2
        {
            float c4;
            double c5;
            float c6;
            signed c7:7;
            signed c8:2;
            short int c9;
            unsigned char c10;
        }
        c13;
    }
    c37
        = {{58732.02}};
static unsigned int c38 = 1650545090U;
static
    union ct5
    {
        double c16;
        float c17[1];
        union ct4 { unsigned char c14; double c15; } c18;
    }
    c39
        = {90842.10};
static int c40 = 1440489150;
static unsigned char c41 = '\x42';
static
    struct ct7
    {
        unsigned long int c23;
        struct ct6
        { double c19; double c20; unsigned long int c21; double c22; }
        c24;
        signed c25:5;
        float c26;
    }
    c42
        =
        {267208072UL,
            {36246.55, 32974.83, 1703731229UL, 72201.81},
            2,
            78260.54};
static unsigned int c43 = 1784012307U;
static union ct8 { float c27; float *c28; } c44 = {63751.42};
static double c45 = 91538.89;
static
    struct ct9
    {
        unsigned short int c29;
        short int c30;
        signed c31:6;
        signed c32:9;
        signed c33:10;
        unsigned long int c34;
        unsigned int c35;
    }
    *c46
        = (struct ct9 *) 269534902U;
float *
callee_c0f(union ct3 cp10,
    unsigned int cp11,
    union ct5 cp12,
    int cp13,
    unsigned char cp14,
    struct ct7 cp15,
    unsigned int cp16,
    union ct8 cp17,
    double cp18,
    struct ct9 *cp19)
{
    
    /* seed: 509898585912647764 */
    QUEST_ASSERT(c37.c11.c0 == cp10.c11.c0);
    QUEST_ASSERT(c38 == cp11);
    QUEST_ASSERT(c39.c16 == cp12.c16);
    QUEST_ASSERT(c40 == cp13);
    QUEST_ASSERT(c41 == cp14);
    QUEST_ASSERT(c42.c23 == cp15.c23);
    QUEST_ASSERT(c42.c24.c19 == cp15.c24.c19);
    QUEST_ASSERT(c42.c24.c20 == cp15.c24.c20);
    QUEST_ASSERT(c42.c24.c21 == cp15.c24.c21);
    QUEST_ASSERT(c42.c24.c22 == cp15.c24.c22);
    QUEST_ASSERT(c42.c25 == cp15.c25);
    QUEST_ASSERT(c42.c26 == cp15.c26);
    QUEST_ASSERT(c43 == cp16);
    QUEST_ASSERT(c44.c27 == cp17.c27);
    QUEST_ASSERT(c45 == cp18);
    QUEST_ASSERT(c46 == cp19);
    return c36;
}
static void caller_c1f()
{
    float *c47; 
    /* seed: 509898585912647764 */
    c47 = callee_c0f(c37, c38, c39, c40, c41, c42, c43, c44, c45, c46);
    QUEST_ASSERT(c36 == c47);
}
static double *b2 = (double *) 791521282U;
static unsigned int (*b3)[2] = (unsigned int (*)[2]) 2002591174U;
static float b4 = 33701.03;
static unsigned char b5 = '\x16';
static unsigned long int b6 = 1274125445UL;
static unsigned long int b7 = 1880957151UL;
static union bt0 { short int b0; long int b1[1]; } b8 = {7879};
static unsigned long int b9[2][1] = {{45906829UL}, {1693819227UL}};
double *
callee_b0f(unsigned int (*bp7)[2],
    float bp8,
    unsigned char bp9,
    unsigned long int bp10,
    unsigned long int bp11,
    union bt0 bp12,
    unsigned long int bp13[2][1])
{
    
    /* seed: 2620 */
    QUEST_ASSERT(b3 == bp7);
    QUEST_ASSERT(b4 == bp8);
    QUEST_ASSERT(b5 == bp9);
    QUEST_ASSERT(b6 == bp10);
    QUEST_ASSERT(b7 == bp11);
    QUEST_ASSERT(b8.b0 == bp12.b0);
    QUEST_ASSERT(b9[1][0] == bp13[1][0]);
    QUEST_ASSERT(b9[0][0] == bp13[0][0]);
    return b2;
}
static void caller_b1f()
{
    double *b10; 
    /* seed: 2620 */
    b10 = callee_b0f(b3, b4, b5, b6, b7, b8, b9);
    QUEST_ASSERT(b2 == b10);
}
int main(int argc, char **argv)
{
    
    caller_u1f();
    caller_t1f();
    caller_s1f();
    caller_r1f();
    caller_q1f();
    caller_p1f();
    caller_o1f();
    caller_n1f();
    caller_m1f();
    caller_l1f();
    caller_k1f();
    caller_j1f();
    caller_i1f();
    caller_h1f();
    caller_g1f();
    caller_f1f();
    caller_e1f();
    caller_d1f();
    caller_c1f();
    caller_b1f();
    return errors;
}
